[package]
name = "deepfrog"
version = "0.1.0"
authors = ["Maarten van Gompel <proycon@anaproy.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-bert = { git = "https://github.com/proycon/rust-bert", branch = "tokclasspipeline" }
clap = "2.33.0"
