language: nld
models:
  - annotation_type: ENTITY
    folia_set: undefined
    model_name: bert-ner-cased-sonar1-nld
    model_type: Bert
    model_local: "bert-ner-cased-sonar1-nld/model.ot"
    model_remote: "https://cdn.huggingface.co/proycon/bert-ner-cased-sonar1-nld/model.ot"
    config_local: "bert-ner-cased-sonar1-nld/config.json"
    config_remote: "https://cdn.huggingface.co/proycon/bert-ner-cased-sonar1-nld/config.json"
    vocab_local: "bert-ner-cased-sonar1-nld/vocab.txt"
    vocab_remote: "https://cdn.huggingface.co/proycon/bert-ner-cased-sonar1-nld/vocab.txt"
    bio: true
    bio_delimiter: "-"
    ignore_label: "O"
  - annotation_type: POS
    folia_set: undefined
    model_name: bert-pos-cased-deepfrog-nld
    model_type: Bert
    model_local: "bert-pos-cased-deepfrog-nld/model.ot"
    model_remote: "https://cdn.huggingface.co/proycon/bert-pos-cased-deepfrog-nld/model.ot"
    config_local: "bert-pos-cased-deepfrog-nld/config.json"
    config_remote: "https://cdn.huggingface.co/proycon/bert-pos-cased-deepfrog-nld/config.json"
    vocab_local: "bert-pos-cased-deepfrog-nld/vocab.txt"
    vocab_remote: "https://cdn.huggingface.co/proycon/bert-pos-cased-deepfrog-nld/vocab.txt"
  - annotation_type: LEMMA
    folia_set: undefined
    model_name: bert-lemma-cased-cgn+elex-nld
    model_type: Bert
    model_local: "bert-lemma-cased-cgn+elex-nld/model.ot"
    model_remote: "https://cdn.huggingface.co/proycon/bert-lemma-cased-cgn+elex-nld/model.ot"
    config_local: "bert-lemma-cased-cgn+elex-nld/config.json"
    config_remote: "https://cdn.huggingface.co/proycon/bert-lemma-cased-cgn+elex-nld/config.json"
    vocab_local: "bert-lemma-cased-cgn+elex-nld/vocab.txt"
    vocab_remote: "https://cdn.huggingface.co/proycon/bert-lemma-cased-cgn+elex-nld/vocab.txt"
    sesdiff: true

