language: eng
models:
  - annotation_type: entity
    folia_set: undefined
    model_name: conll03
    model_type: Bert
    model_local: "bert-large-cased-finetuned-conll03-english/rust_model.ot"
    model_remote: "https://cdn.huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english/rust_model.ot"
    config_local: "bert-large-cased-finetuned-conll03-english/config.json"
    config_remote: "https://cdn.huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english/config.json"
    vocab_local: "bert-large-cased-finetuned-conll03-english/vocab.txt"
    vocab_remote: "https://cdn.huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english/vocab.txt"
    ignore_first_label: true

